sylius_grid:
  grids:
    app_admin_colorproperty:
      driver:
        options:
          class: "%app.model.colorproperty.class%"
      fields:
        color:
          type: string
          label: sylius.ui.color
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update  
          delete:
            type: delete